USE south_stand;
SET NAMES utf8mb4;

DROP TEMPORARY TABLE IF EXISTS t17_complete_matches;
CREATE TEMPORARY TABLE t17_complete_matches AS
SELECT m.id match_id
FROM match_info m
WHERE m.match_status='FINISHED' AND m.status='ACTIVE' AND m.is_deleted=0
  AND (SELECT COUNT(*) FROM football_match_lineup l WHERE l.match_id=m.id AND l.is_deleted=0)=2
  AND (SELECT COUNT(*) FROM football_match_player_appearance a WHERE a.match_id=m.id AND a.lineup_type='STARTER' AND a.status='ACTIVE' AND a.is_deleted=0)=22
  AND (SELECT COUNT(*) FROM football_match_player_appearance a WHERE a.match_id=m.id AND a.lineup_type IN('SUBSTITUTE','BENCH') AND a.status='ACTIVE' AND a.is_deleted=0)>=10
  AND (SELECT COUNT(*) FROM football_match_player_appearance a WHERE a.match_id=m.id AND a.team_id=m.home_team_id AND a.lineup_type='STARTER' AND a.status='ACTIVE' AND a.is_deleted=0)=11
  AND (SELECT COUNT(*) FROM football_match_player_appearance a WHERE a.match_id=m.id AND a.team_id=m.away_team_id AND a.lineup_type='STARTER' AND a.status='ACTIVE' AND a.is_deleted=0)=11
  AND (SELECT COUNT(*) FROM football_match_player_appearance a WHERE a.match_id=m.id AND a.team_id=m.home_team_id AND a.lineup_type IN('SUBSTITUTE','BENCH') AND a.status='ACTIVE' AND a.is_deleted=0)>=5
  AND (SELECT COUNT(*) FROM football_match_player_appearance a WHERE a.match_id=m.id AND a.team_id=m.away_team_id AND a.lineup_type IN('SUBSTITUTE','BENCH') AND a.status='ACTIVE' AND a.is_deleted=0)>=5
  AND (SELECT COUNT(*) FROM football_match_team_stat t WHERE t.match_id=m.id AND t.is_deleted=0)=2
  AND NOT EXISTS (SELECT 1 FROM football_match_player_appearance a LEFT JOIN football_match_player_stat p ON p.match_id=a.match_id AND p.player_id=a.player_id AND p.is_deleted=0 WHERE a.match_id=m.id AND a.appeared_flag=1 AND a.status='ACTIVE' AND a.is_deleted=0 AND p.id IS NULL);

SELECT check_name,anomaly_count FROM (
 SELECT 'lineup_team_not_in_match' check_name,COUNT(*) anomaly_count FROM football_match_lineup l JOIN match_info m ON m.id=l.match_id WHERE l.is_deleted=0 AND l.team_id NOT IN(m.home_team_id,m.away_team_id)
 UNION ALL SELECT 'lineup_duplicate_active',COUNT(*) FROM (SELECT match_id,team_id FROM football_match_lineup WHERE is_deleted=0 GROUP BY match_id,team_id HAVING COUNT(*)>1)x
 UNION ALL SELECT 'appearance_missing_relation',COUNT(*) FROM football_match_player_appearance a LEFT JOIN match_info m ON m.id=a.match_id LEFT JOIN football_player p ON p.id=a.player_id LEFT JOIN football_season s ON s.league_id=m.league_id AND s.current_flag=1 AND s.is_deleted=0 LEFT JOIN football_team_season_player r ON r.season_id=s.id AND r.team_id=a.team_id AND r.player_id=a.player_id AND r.status='ACTIVE' AND r.is_deleted=0 WHERE a.is_deleted=0 AND (m.id IS NULL OR p.id IS NULL OR a.team_id NOT IN(m.home_team_id,m.away_team_id) OR r.id IS NULL)
 UNION ALL SELECT 'appearance_duplicate_match_player',COUNT(*) FROM (SELECT match_id,player_id FROM football_match_player_appearance WHERE is_deleted=0 GROUP BY match_id,player_id HAVING COUNT(*)>1)x
 UNION ALL SELECT 'appearance_multiple_captains',COUNT(*) FROM (SELECT match_id,team_id FROM football_match_player_appearance WHERE status='ACTIVE' AND is_deleted=0 AND captain_flag=1 GROUP BY match_id,team_id HAVING COUNT(*)>1)x
 UNION ALL SELECT 'appearance_invalid_starter',COUNT(*) FROM football_match_player_appearance WHERE is_deleted=0 AND lineup_type='STARTER' AND (started_flag<>1 OR appeared_flag<>1 OR start_minute<>0)
 UNION ALL SELECT 'appearance_invalid_time',COUNT(*) FROM football_match_player_appearance WHERE is_deleted=0 AND (start_minute<0 OR end_minute<start_minute OR substituted_in_minute<0 OR substituted_out_minute<0 OR substituted_in_minute>120 OR substituted_out_minute>120)
 UNION ALL SELECT 'team_stat_invalid_counts',COUNT(*) FROM football_match_team_stat WHERE is_deleted=0 AND (shots<shots_on_target OR passes<successful_passes OR shots<0 OR corners<0 OR fouls<0 OR offsides<0 OR yellow_cards<0 OR red_cards<0 OR passes<0 OR saves<0)
 UNION ALL SELECT 'team_stat_bad_pass_accuracy',COUNT(*) FROM football_match_team_stat WHERE is_deleted=0 AND ((passes=0 AND pass_accuracy IS NOT NULL) OR (passes>0 AND ABS(pass_accuracy-successful_passes*100.0/passes)>0.02))
 UNION ALL SELECT 'team_stat_bad_possession',COUNT(*) FROM (SELECT match_id,SUM(possession) possession,COUNT(*) c FROM football_match_team_stat WHERE is_deleted=0 GROUP BY match_id HAVING c=2 AND ABS(possession-100)>0.02)x
 UNION ALL SELECT 'player_stat_without_appearance',COUNT(*) FROM football_match_player_stat s LEFT JOIN football_match_player_appearance a ON a.match_id=s.match_id AND a.player_id=s.player_id AND a.status='ACTIVE' AND a.is_deleted=0 WHERE s.is_deleted=0 AND (a.id IS NULL OR a.appeared_flag<>1 OR a.team_id<>s.team_id OR a.end_minute-a.start_minute<>s.minutes)
 UNION ALL SELECT 'player_stat_invalid_values',COUNT(*) FROM football_match_player_stat WHERE is_deleted=0 AND (shots<shots_on_target OR goals>shots_on_target OR passes<successful_passes OR minutes<0 OR goals<0 OR assists<0 OR official_rating<5 OR official_rating>9.5)
 UNION ALL SELECT 'match_score_player_goal_mismatch',COUNT(*) FROM match_info m JOIN (SELECT match_id,team_id,SUM(goals) goals FROM football_match_player_stat WHERE is_deleted=0 GROUP BY match_id,team_id)s ON s.match_id=m.id WHERE s.goals<>IF(s.team_id=m.home_team_id,COALESCE(m.home_score,0),COALESCE(m.away_score,0))
 UNION ALL SELECT 'event_goal_player_stat_mismatch',COUNT(*) FROM (SELECT s.match_id,s.player_id,s.goals,COUNT(e.id) event_goals FROM football_match_player_stat s LEFT JOIN match_event e ON e.match_id=s.match_id AND e.player_id=s.player_id AND e.event_type='GOAL' AND e.status='ACTIVE' AND e.is_deleted=0 WHERE s.is_deleted=0 GROUP BY s.match_id,s.player_id,s.goals HAVING goals<>event_goals)x
 UNION ALL SELECT 'event_card_player_stat_mismatch',COUNT(*) FROM (SELECT s.match_id,s.player_id,s.yellow_cards,s.red_cards,SUM(e.event_type='YELLOW_CARD') ey,SUM(e.event_type='RED_CARD') er FROM football_match_player_stat s LEFT JOIN match_event e ON e.match_id=s.match_id AND e.player_id=s.player_id AND e.event_type IN('YELLOW_CARD','RED_CARD') AND e.status='ACTIVE' AND e.is_deleted=0 WHERE s.is_deleted=0 GROUP BY s.match_id,s.player_id,s.yellow_cards,s.red_cards HAVING yellow_cards<>ey OR red_cards<>er)x
 UNION ALL SELECT 'team_player_stat_mismatch',COUNT(*) FROM football_match_team_stat t JOIN (SELECT match_id,team_id,SUM(shots) shots,SUM(shots_on_target) sot,SUM(yellow_cards) yc,SUM(red_cards) rc,SUM(passes) passes,SUM(successful_passes) sp,SUM(saves) saves FROM football_match_player_stat WHERE is_deleted=0 GROUP BY match_id,team_id)p ON p.match_id=t.match_id AND p.team_id=t.team_id WHERE t.is_deleted=0 AND (t.shots<>p.shots OR t.shots_on_target<>p.sot OR t.yellow_cards<>p.yc OR t.red_cards<>p.rc OR t.passes<>p.passes OR t.successful_passes<>p.sp OR t.saves<>p.saves)
 UNION ALL SELECT 'player_match_totals_exceed_t15',COUNT(*) FROM (SELECT m.league_id,se.id season_id,s.team_id,s.player_id,COUNT(*) appearances,SUM(s.minutes) minutes,SUM(s.goals) goals,SUM(s.assists) assists,SUM(s.shots) shots,SUM(s.shots_on_target) sot,SUM(s.yellow_cards) yc,SUM(s.red_cards) rc,SUM(s.saves) saves FROM football_match_player_stat s JOIN match_info m ON m.id=s.match_id JOIN football_season se ON se.league_id=m.league_id AND se.current_flag=1 AND se.is_deleted=0 WHERE s.is_deleted=0 GROUP BY m.league_id,se.id,s.team_id,s.player_id)x LEFT JOIN football_player_competition_stat p ON p.league_id=x.league_id AND p.season_id=x.season_id AND p.team_id=x.team_id AND p.player_id=x.player_id AND p.is_deleted=0 WHERE p.id IS NULL OR x.appearances>p.appearances OR x.minutes>p.minutes OR x.goals>p.goals OR x.assists>p.assists OR x.shots>p.shots OR x.sot>p.shots_on_target OR x.yc>p.yellow_cards OR x.rc>p.red_cards OR x.saves>p.saves
 UNION ALL SELECT 'rating_invalid_value',COUNT(*) FROM football_user_player_rating WHERE status='ACTIVE' AND is_deleted=0 AND (rating<1 OR rating>10 OR MOD(rating*2,1)<>0)
 UNION ALL SELECT 'rating_ineligible_player_or_match',COUNT(*) FROM football_user_player_rating r LEFT JOIN match_info m ON m.id=r.match_id LEFT JOIN football_match_player_appearance a ON a.match_id=r.match_id AND a.player_id=r.player_id AND a.status='ACTIVE' AND a.is_deleted=0 WHERE r.status='ACTIVE' AND r.is_deleted=0 AND (m.match_status<>'FINISHED' OR a.id IS NULL OR a.appeared_flag<>1)
 UNION ALL SELECT 'rating_duplicate_active',COUNT(*) FROM (SELECT user_id,match_id,player_id FROM football_user_player_rating WHERE status='ACTIVE' AND is_deleted=0 GROUP BY user_id,match_id,player_id HAVING COUNT(*)>1)x
 UNION ALL SELECT 'active_ratings_below_300',IF(COUNT(*)>=300,0,1) FROM football_user_player_rating WHERE status='ACTIVE' AND is_deleted=0
 UNION ALL SELECT 'rating_demo_users_below_15',IF(COUNT(DISTINCT user_id)>=15,0,1) FROM football_user_player_rating WHERE status='ACTIVE' AND is_deleted=0
) checks ORDER BY check_name;

SELECT 'complete_match_roster_below_18' check_name,COUNT(*) anomaly_count FROM (SELECT c.match_id,a.team_id,s.id season_id,COUNT(DISTINCT r.player_id) n FROM t17_complete_matches c JOIN match_info m ON m.id=c.match_id JOIN football_season s ON s.league_id=m.league_id AND s.current_flag=1 JOIN football_match_player_appearance a ON a.match_id=c.match_id JOIN football_team_season_player r ON r.season_id=s.id AND r.team_id=a.team_id AND r.status='ACTIVE' AND r.is_deleted=0 GROUP BY c.match_id,a.team_id,s.id HAVING n<18)x;
SELECT 'complete_match_starter_count' check_name,COUNT(*) anomaly_count FROM (SELECT a.match_id,a.team_id,COUNT(*) n FROM football_match_player_appearance a JOIN t17_complete_matches c ON c.match_id=a.match_id WHERE a.lineup_type='STARTER' AND a.status='ACTIVE' AND a.is_deleted=0 GROUP BY a.match_id,a.team_id HAVING n<>11)x;
SELECT 'complete_match_bench_count' check_name,COUNT(*) anomaly_count FROM (SELECT a.match_id,a.team_id,COUNT(*) n FROM football_match_player_appearance a JOIN t17_complete_matches c ON c.match_id=a.match_id WHERE a.lineup_type IN('SUBSTITUTE','BENCH') AND a.status='ACTIVE' AND a.is_deleted=0 GROUP BY a.match_id,a.team_id HAVING n<5)x;
SELECT 'starter_missing_goalkeeper' check_name,COUNT(*) anomaly_count FROM (SELECT a.match_id,a.team_id,SUM(a.position='GOALKEEPER') n FROM football_match_player_appearance a JOIN t17_complete_matches c ON c.match_id=a.match_id WHERE a.lineup_type='STARTER' AND a.status='ACTIVE' AND a.is_deleted=0 GROUP BY a.match_id,a.team_id HAVING n<>1)x;
SELECT 'bench_missing_goalkeeper' check_name,COUNT(*) anomaly_count FROM (SELECT a.match_id,a.team_id,SUM(a.position='GOALKEEPER') n FROM football_match_player_appearance a JOIN t17_complete_matches c ON c.match_id=a.match_id WHERE a.lineup_type IN('SUBSTITUTE','BENCH') AND a.status='ACTIVE' AND a.is_deleted=0 GROUP BY a.match_id,a.team_id HAVING n<1)x;
SELECT 'starter_formation_invalid' check_name,COUNT(*) anomaly_count FROM (SELECT a.match_id,a.team_id,SUM(a.position='DEFENDER') df,SUM(a.position='MIDFIELDER') mf,SUM(a.position='FORWARD') fw FROM football_match_player_appearance a JOIN t17_complete_matches c ON c.match_id=a.match_id WHERE a.lineup_type='STARTER' AND a.status='ACTIVE' AND a.is_deleted=0 GROUP BY a.match_id,a.team_id HAVING df<>4 OR mf<>3 OR fw<>3)x;
SELECT 'substitution_appearance_mismatch' check_name,COUNT(*) anomaly_count FROM match_event e JOIN t17_complete_matches c ON c.match_id=e.match_id LEFT JOIN football_match_player_appearance a ON a.match_id=e.match_id AND a.player_id=e.player_id AND a.status='ACTIVE' AND a.is_deleted=0 WHERE e.event_type='SUBSTITUTION' AND e.status='ACTIVE' AND e.is_deleted=0 AND (a.id IS NULL OR a.substituted_out_minute<>e.minute OR a.end_minute<>e.minute);
SELECT 'complete_matches_below_12' check_name,IF(COUNT(*)>=12,0,1) anomaly_count FROM t17_complete_matches;
