"""Generate deterministic, incremental T18 behavior data from existing demo ID ranges."""

from pathlib import Path
from datetime import datetime, timedelta

USERS = [11_000_000_000_000_000 + i for i in range(1, 21)]
CONTENTS = [16_000_000_000_000_000 + i for i in range(1, 121)]
OUTPUT = Path(__file__).parent / "sql" / "seed-t18-recommendation-incremental.sql"
BASE_TIME = datetime(2026, 8, 21, 12, 0, 0)


def sql_value(value):
    if value is None:
        return "NULL"
    if isinstance(value, str):
        return "'" + value.replace("'", "''") + "'"
    return str(value)


def main():
    rows = []
    event_number = 0
    for user_index, user_id in enumerate(USERS):
        cluster_start = (user_index % 4) * 30
        preferred = CONTENTS[cluster_start:cluster_start + 30]
        for sequence in range(150):
            # Three out of four impressions stay in the user's interest cluster.
            content_id = (preferred[(sequence * 7 + user_index) % len(preferred)]
                          if sequence % 4 else CONTENTS[(sequence * 11 + user_index) % len(CONTENTS)])
            event_time = BASE_TIME - timedelta(days=sequence % 29, minutes=user_index * 11 + sequence)
            common = (user_id, content_id, event_time)
            event_number = append(rows, event_number, "EXPOSE", common, None)
            if sequence % 2 == 0:
                event_number = append(rows, event_number, "CLICK", common, None)
            if sequence % 3 == 0:
                event_number = append(rows, event_number, "DETAIL", common, 8_000 + (sequence % 53) * 1_000)
            if sequence % 10 == 0:
                event_number = append(rows, event_number, "LIKE", common, None)
            if sequence % 20 == 0:
                event_number = append(rows, event_number, "FAVORITE", common, None)
            if sequence % 30 == 0:
                event_number = append(rows, event_number, "COMMENT", common, None)

    columns = "(id,client_event_id,user_id,session_id,behavior_type,target_type,target_id,scene,algorithm_version,model_version,experiment_id,experiment_bucket,request_id,impression_id,position,dwell_ms,event_time,extra_json,status,is_deleted)"
    lines = [
        "-- T18 deterministic incremental behavior seed: 20 users, 120 contents, 6060 events.",
        "-- Generated by scripts/generate_t18_recommendation_seed.py; INSERT IGNORE + fixed client IDs makes reruns idempotent.",
        "SET NAMES utf8mb4;",
        "USE south_stand;",
        "",
    ]
    for start in range(0, len(rows), 250):
        values = rows[start:start + 250]
        lines.append(f"INSERT IGNORE INTO user_behavior_log {columns} VALUES")
        lines.append(",\n".join("(" + ",".join(sql_value(v) for v in row) + ")" for row in values) + ";")
        lines.append("")
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"generated {len(rows)} deterministic T18 events at {OUTPUT}")


def append(rows, event_number, behavior, common, dwell_ms):
    user_id, content_id, event_time = common
    event_number += 1
    bucket = "B" if user_id % 2 == 0 else "A"
    rows.append((
        2_180_000_000_000_000_000 + event_number,
        f"t18-demo-{event_number:06d}", user_id, f"t18-session-{user_id}-{event_time.day}",
        behavior, "CONTENT", content_id, "HOME_RECOMMEND", "RULE_V2", None,
        "REC_HOME_V1", bucket, f"t18-request-{user_id}-{event_time.day}",
        f"t18-impression-{event_number:06d}", event_number % 20, dwell_ms,
        event_time.strftime("%Y-%m-%d %H:%M:%S"), '{"source":"T18_DEMO"}', "ACTIVE", 0,
    ))
    return event_number


if __name__ == "__main__":
    main()
